import type { Metadata } from "next";
import Sidebar from '@/components/Sidebar';
import ConversationsList from './components/ConversationsList';
import getConversations from '@/actions/getConversations';
import getUsers from "@/actions/getUsers";

export const metadata: Metadata = {
    title: 'Night Messenger Conversations',
    description: 'Generated by create next app',
}

export default async function ConversationsLayout({
    children
}:{
    children: React.ReactNode
}){
    const conversation = await getConversations();
    const users = await getUsers();
    return (
        <Sidebar>
            <div className="h-full">
                <ConversationsList 
                    users={users}
                    conversations={conversation}
                    messages={"Messages"}
                />
                {children}
            </div>
        </Sidebar>
    )
}