import type { Metadata } from 'next';
import Sidebar from '@/components/Sidebar';
import getUsers from '@/actions/getUsers';
import UserList from './components/UserList';
import { getTranslations } from "next-intl/server";

export const metadata: Metadata = {
    title: 'Night Messenger Users',
    description: 'Generated by create next app',
}

export default async function Layout({
    children
}:{
    children: React.ReactNode
}) {
    const users = await getUsers();
    const t = await getTranslations ('State');
    return (
        <Sidebar>
            <div className="h-full">
                <UserList 
                    usersList={users} 
                    people={t('people')}
                />
                {children}
            </div>
        </Sidebar>
    )
}