import type { Metadata } from 'next';
import Script from 'next/script';
import { direction } from '@/i18n';
import ThemesProvider from '@/context/ThemeContext';
import ToasterContext from '@/context/ToasterContext';
import AuthContext from '@/context/AuthContext';
import ActiveStatus from '@/components/ActiveStatus';
import './globals.css'

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

export const metadata: Metadata = {
    title: 'Night Messenger',
    description: 'Generated by create next app',
}

export default function LocaleLayout({
        children,
        params: {locale}
}: {
    children: React.ReactNode;
    params: {locale: string};
}) {

    const d = direction(locale);
    
    return (
        <html lang={locale} dir={d} suppressHydrationWarning>
            <body>
                <AuthContext>
                    <ThemesProvider>
                        <ToasterContext />
                        <ActiveStatus />
                        {children}
                    </ThemesProvider>
                </AuthContext>
                <Script src='/js/service-worker.js'/>
            </body>
        </html>
    )
}
